"""Intent exemplars for semantic intent routing."""

INTENT_EXEMPLARS = {
    "PRODUCT_RAG": [
        # Formal queries
        "What coffee do you recommend?",
        "Tell me about your espresso options",
        "I'm looking for a decaf drink",
        "What's your strongest coffee?",
        "Something sweet for the afternoon",
        "What pairs well with breakfast?",
        "Tell me about your seasonal drinks",
        "I need something with lots of caffeine",
        "What's the difference between a latte and cappuccino?",
        "Do you have any cold brew options?",
        "I want something with chocolate",
        "What's your most popular drink?",
        "Tell me about your coffee beans",
        "What's good for someone who doesn't like coffee?",
        "Do you have any sugar-free options?",
        # Casual/idiomatic expressions
        "I need something bold",
        "I need something strong",
        "caffeine please",
        "gimme anything",
        "what's good here?",
        "surprise me",
        "I'm tired, help",
        "need my fix",
        "hook me up",
        "what's brewing?",
        "hit me with your best shot",
        "I need to wake up",
        "something to get me going",
        "dealer's choice",
        "I'll take whatever",
        "just give me coffee",
        "anything with a kick",
        "make it strong",
        "double shot of anything",
        "I'm dragging today",
        "need some rocket fuel",
        "what's fresh?",
        "what do you got?",
        "coffee me",
        "bean juice please",
        # Typos and misspellings
        "coffe recommendations",
        "expresso options",
        "whats ur best seller",
        "capuccino or latte",
        "cold cofee options",
        "decaff drinks",
        # Context-specific
        "morning pick-me-up suggestions",
        "something to pair with dessert",
        "drinks for lactose intolerant",
        "coffee for studying late",
        "best drink for a hot day",
        "warming drinks for winter",
        # Multi-word entities
        "flat white vs cortado difference",
        "iced americano with oat milk",
        "vanilla latte extra shot",
        "caramel macchiato decaf",
        "matcha latte with almond milk",
        # Indirect queries
        "I'm sleepy what should I get",
        "first time here what's good",
        "help me choose something sweet",
        "I usually drink tea any suggestions",
        "not a coffee person what else",
        # Specific preferences
        "low calorie coffee options",
        "keto friendly drinks",
        "vegan drink options",
        "protein coffee choices",
        "organic coffee selections",
        "i need something light",
    ],
    "GENERAL_CONVERSATION": [
        # Greetings and pleasantries
        "How are you today?",
        "Tell me a coffee joke",
        "What's your name?",
        "Thanks for your help",
        "That sounds great",
        "Can you help me?",
        "Hello",
        "Good morning",
        "Goodbye",
        "What can you do?",
        "Tell me about yourself",
        "That's interesting",
        "I see",
        "Never mind",
        "Sorry",
        "hey",
        "sup",
        "yo",
        "what's up",
        "howdy",
        "thanks",
        "thank you",
        "appreciate it",
        "cool",
        "nice",
        "awesome",
        "perfect",
    ],
}
