[project]
authors = [{ name = "Cody Fincher", email = "cody.fincher@gmail.com" }]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Web Environment",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Software Development",
    "Typing :: Typed",
]
dependencies = [
    "litestar[jinja,jwt,redis,cryptography,structlog,pydantic,sqlalchemy]",
    "litestar-oracledb",
    "litestar-granian[uvloop]",
    "litestar-vite[nodeenv]",
    "python-dotenv",
    "httptools",
    "google-cloud-aiplatform>=1.38.0",
    "google-generativeai>=0.3.2",
    "vertexai",
    "numpy",
    "prompt-toolkit",
    "aiosqlite",
]
description = "Reference application for Oracle 23AI and VertexAI integration."
keywords = ["litestar", "vertexai", "oracledb", "google"]
license = { text = "MIT" }
maintainers = [{ name = "Cody Fincher", email = "cody.fincher@gmail.com" }]
name = "app"
readme = "README.md"
requires-python = ">=3.11,<3.13"
version = "0.2.0"

[project.scripts]
app = "app.__init__:run_cli"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "nodeenv"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build]
dev-mode-dirs = ["./"]
include = ["CHANGELOG.md", "/public/**/*", "/app/**/*.sql", "/app/db/**/*.ini"]
packages = ["app"]

[dependency-groups]
build = ["bump-my-version"]
dev = [
    { include-group = "extras" },
    { include-group = "lint" },
    { include-group = "test" },
    { include-group = "build" },
]
extras = []
lint = ["mypy", "pre-commit", "pyright", "ruff", "slotscheck", "types-click"]
test = [
    "anyio",
    "coverage",
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-databases[valkey,oracle]",
    "pytest-mock",
    "pytest-sugar",
    "pytest-xdist",
]

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pycache__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "app/db/migrations/versions/*.py",
]
fix = true
line-length = 120
src = ["."]
target-version = "py311"

[tool.ruff.lint]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
fixable = ["ALL"]
ignore = [
    "E501",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D202",
    "D205",
    "D415",
    "UP037",
    "A003",
    "B010",
    "B008",
    "RUF012",
    "ANN401",
    "ANN102",
    "ANN101",
    "PLR0913",
    "PLR2004",
    "FBT001",
    "FBT002",
    "FBT003",
    "ARG002",
    "ARG001",
    "TD002",
    "TD003",
    "FIX002",
    "PGH003",
    "RUF006",
    "SLF001",
    "PT007",
    "PT004",
    "PT005",
    "S603",
    "PLW2901",
    "FBT",
    "PT",
    "TD",
    "PERF203",
]
select = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 12

[tool.ruff.lint.pep8-naming]
classmethod-decorators = [
    "classmethod",
    "sqlalchemy.ext.declarative.declared_attr",
    "sqlalchemy.orm.declared_attr.directive",
    "sqlalchemy.orm.declared_attr",
]

[tool.ruff.lint.isort]
known-first-party = ["tests", "app", "config"]

[tool.ruff.lint.per-file-ignores]
"*/migrations/*.py" = ["D104", "D103", "D205", "D212"]
"__init__.py" = ["F401", "D104"]
"app/db/migrations/versions/*.py" = ["ANN201", "INP001"]
"docs/**/*.*" = ["S", "B", "DTZ", "A", "TCH", "ERA", "D", "RET", "E731", "RUF012", "FA100", "ARG001"]
"docs/conf.py" = ["FIX002", "ARG001", "INP001"]
"scripts/*.py" = ["INP001", "ERA001"]
"scripts/**/*.*" = ["D", "ARG", "EM", "TRY", "G", "FBT", "INP001"]
"tests/*.py" = ["D103", "S101", "D104"]

[tool.slotscheck]
strict-imports = false

[tool.codespell]
ignore-words-list = "alog"
skip = 'pdm.lock, package-lock.json'

[tool.mypy]
disallow_any_generics = false
disallow_incomplete_defs = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
exclude = '''(?x)(
^build/
|^dist/
|^.venv/
|^node_modules/
|^migrations/
)'''
implicit_reexport = false
plugins = []
strict = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
disallow_untyped_decorators = false
module = ["tests.*"]

[[tool.mypy.overrides]]
disallow_untyped_calls = false
disallow_untyped_decorators = false
module = ["aisoql.*"]

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
    "sqlalchemy.*",
    "saq.*",
    "uvicorn.*",
    "aiohttp.*",
    "jsbeautifier",
    "jsbeautifier.*",
    "uvloop",
    "uvloop.*",
    "nodeenv",
]

[[tool.mypy.overrides]]
ignore_errors = true
module = ["app.db.migrations.*"]

[tool.pytest.ini_options]
addopts = ["-ra", "--ignore", "app/db/migrations"]
filterwarnings = [
    "ignore::DeprecationWarning:pkg_resources",
    "ignore::DeprecationWarning:google.*",
    "ignore::PendingDeprecationWarning",
    "ignore::UserWarning:sqlalchemy.*",
]
testpaths = ["tests"]

[tool.pyright]
exclude = ["scripts", "docs"]
include = ["app", "tests"]
