-- SPDX-FileCopyrightText: 2026 Google LLC
-- SPDX-License-Identifier: Apache-2.0

-- SQLSpec Migration
-- Version: 0001
-- Description: Cymball Coffee Products
-- Created: 2025-10-19T20:42:18.358307+00:00
-- Author: Cody Fincher <cody@litestar.dev>

-- name: migrate-0001-up
CREATE TABLE product (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(4000),
    price NUMBER(10, 2),
    category VARCHAR2(100),
    sku VARCHAR2(100) UNIQUE,
    in_stock BOOLEAN DEFAULT TRUE
        ANNOTATIONS (
            Display 'Global stock fallback',
            Data_Role 'availability'
        ),
    metadata JSON,
    -- docs:start-schema-annotations
    embedding VECTOR(3072, FLOAT32)
        ANNOTATIONS (
            Display 'Product embedding',
            Embedding_Model 'gemini-embedding-2',
            Embedding_Dimensions '3072',
            Embedding_Purpose 'document',
            Distance 'COSINE'
        ),
    -- docs:end-schema-annotations
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT ON NULL FOR INSERT AND UPDATE CURRENT_TIMESTAMP NOT NULL
) INMEMORY PRIORITY HIGH
ANNOTATIONS (
    Display 'Cymbal Coffee products',
    Description 'Menu catalog rows with Vertex embeddings for semantic search',
    AI_Surface 'PRODUCT_RAG'
);

COMMENT ON TABLE product IS 'Products with vector embeddings for semantic search';
COMMENT ON COLUMN product.embedding IS '3072-dimensional gemini-embedding-2 vector';
COMMENT ON COLUMN product.in_stock IS 'Boolean: true=in stock, false=out of stock';


-- Store locations for coffee shop finder
CREATE TABLE store (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    address VARCHAR2(500) NOT NULL,
    city VARCHAR2(100),
    state VARCHAR2(50),
    zip VARCHAR2(20),
    phone VARCHAR2(50),
    latitude NUMBER(9, 6)
        ANNOTATIONS (
            Display 'Store latitude',
            Privacy 'Seeded store coordinate only'
        ),
    longitude NUMBER(9, 6)
        ANNOTATIONS (
            Display 'Store longitude',
            Privacy 'Seeded store coordinate only'
        ),
    timezone VARCHAR2(64)
        ANNOTATIONS (
            Display 'Store timezone',
            Data_Role 'hours'
        ),
    google_place_id VARCHAR2(255)
        ANNOTATIONS (
            Display 'Google Place ID',
            Maps_Baseline 'No-key Maps URLs use address data'
        ),
    hours JSON
        ANNOTATIONS (
            Display 'Business hours',
            Data_Role 'store_hours'
        ),
    metadata JSON,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT ON NULL FOR INSERT AND UPDATE CURRENT_TIMESTAMP NOT NULL
)
ANNOTATIONS (
    Display 'Cymbal Coffee stores',
    Description 'Seeded cafe locations for store-aware chat and maps actions'
);

COMMENT ON TABLE store IS 'Coffee shop store locations';
COMMENT ON COLUMN store.latitude IS 'Approximate store latitude for local nearest-store ranking; browser coordinates are request-scoped only';
COMMENT ON COLUMN store.longitude IS 'Approximate store longitude for local nearest-store ranking; browser coordinates are request-scoped only';
COMMENT ON COLUMN store.timezone IS 'IANA timezone used to interpret store hours';
COMMENT ON COLUMN store.google_place_id IS 'Optional Google Place ID for future Maps integrations; no-key Maps URLs can use address data';
COMMENT ON COLUMN store.hours IS 'Business hours by day: {"monday": "7am-9pm", ...}';
COMMENT ON COLUMN store.metadata IS 'Additional store metadata in JSON format';


-- Store-level product inventory for grounded availability answers
CREATE TABLE store_product_inventory (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    store_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity_available NUMBER(10) DEFAULT 0 NOT NULL
        ANNOTATIONS (
            Display 'Pickup quantity',
            Data_Role 'availability'
        ),
    stock_status VARCHAR2(20) NOT NULL
        ANNOTATIONS (
            Display 'Stock status',
            Enum_Values 'IN_STOCK, LOW_STOCK, OUT_OF_STOCK'
        ),
    pickup_available BOOLEAN DEFAULT TRUE NOT NULL
        ANNOTATIONS (
            Display 'Pickup available',
            Data_Role 'availability'
        ),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT ON NULL FOR INSERT AND UPDATE CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT store_product_inventory_store_fk FOREIGN KEY (store_id) REFERENCES store (id) ON DELETE CASCADE,
    CONSTRAINT store_product_inventory_product_fk FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE,
    CONSTRAINT store_product_inventory_uk UNIQUE (store_id, product_id),
    CONSTRAINT store_product_inventory_status_ck CHECK (stock_status IN ('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK')),
    CONSTRAINT store_product_inventory_qty_ck CHECK (quantity_available >= 0)
)
ANNOTATIONS (
    Display 'Store product inventory',
    Description 'Curated store-level availability for deterministic chat grounding'
);

COMMENT ON TABLE store_product_inventory IS 'Curated store-level product availability for deterministic chat grounding';
COMMENT ON COLUMN store_product_inventory.quantity_available IS 'Current known pickup quantity for this product at this store';
COMMENT ON COLUMN store_product_inventory.stock_status IS 'Inventory status enum: IN_STOCK, LOW_STOCK, or OUT_OF_STOCK';
COMMENT ON COLUMN store_product_inventory.pickup_available IS 'Whether this product can currently be reserved for pickup at this store';


-- Response cache for LLM responses
CREATE TABLE response_cache (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cache_key VARCHAR2(255) UNIQUE NOT NULL
        ANNOTATIONS (
            Display 'Response cache key',
            Privacy 'No browser coordinates'
        ),
    response_data JSON NOT NULL
        ANNOTATIONS (
            Display 'Cached response payload',
            Cache_Role 'llm_response'
        ),
    expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT ON NULL FOR INSERT AND UPDATE CURRENT_TIMESTAMP NOT NULL
)  INMEMORY PRIORITY HIGH
ANNOTATIONS (
    Display 'Response cache',
    Cache_Role 'llm_response'
);

COMMENT ON TABLE response_cache IS 'Cached LLM responses to reduce API calls';
COMMENT ON COLUMN response_cache.cache_key IS 'Hash of query + context for cache lookup';


-- Embedding cache for vector embeddings
CREATE TABLE embedding_cache (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    text_hash VARCHAR2(255) NOT NULL
        ANNOTATIONS (
            Display 'Embedding text hash',
            Privacy 'Source text hash only'
        ),
    embedding VECTOR(3072, FLOAT32) NOT NULL
        ANNOTATIONS (
            Display 'Cached embedding',
            Embedding_Model 'gemini-embedding-2',
            Embedding_Dimensions '3072'
        ),
    model VARCHAR2(100) NOT NULL
        ANNOTATIONS (
            Display 'Embedding model'
        ),
    hit_count NUMBER DEFAULT 0,
    last_accessed TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT embedding_cache_uk UNIQUE (text_hash, model)
)  INMEMORY PRIORITY HIGH
ANNOTATIONS (
    Display 'Embedding cache',
    Cache_Role 'vertex_embeddings'
);

COMMENT ON TABLE embedding_cache IS 'Cached embeddings to reduce Vertex AI API calls';
COMMENT ON COLUMN embedding_cache.text_hash IS 'SHA256 hash of input text';
COMMENT ON COLUMN embedding_cache.embedding IS '3072-dimensional gemini-embedding-2 vector';


-- Search metrics for performance tracking
CREATE TABLE search_metric (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    query_id VARCHAR2(255) NOT NULL
        ANNOTATIONS (
            Display 'Search query identifier'
        ),
    user_id VARCHAR2(255)
        ANNOTATIONS (
            Display 'Session user identifier',
            Privacy 'Application user/session id only'
        ),
    search_time_ms NUMBER
        ANNOTATIONS (
            Display 'Total search time in milliseconds'
        ),
    embedding_time_ms NUMBER
        ANNOTATIONS (
            Display 'Vertex embedding time in milliseconds'
        ),
    oracle_time_ms NUMBER
        ANNOTATIONS (
            Display 'Oracle vector search time in milliseconds'
        ),
    ai_time_ms NUMBER DEFAULT 0,
    intent_time_ms NUMBER DEFAULT 0,
    similarity_score NUMBER
        ANNOTATIONS (
            Display 'Representative similarity score'
        ),
    result_count NUMBER
        ANNOTATIONS (
            Display 'Returned result count'
        ),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT ON NULL FOR INSERT AND UPDATE CURRENT_TIMESTAMP NOT NULL
)
ANNOTATIONS (
    Display 'Search metrics',
    Description 'Vector-search and chat-routing telemetry without raw location storage'
);

COMMENT ON TABLE search_metric IS 'Search performance metrics for vector search operations';
COMMENT ON COLUMN search_metric.query_id IS 'Unique identifier for each search query';
COMMENT ON COLUMN search_metric.user_id IS 'User or session performing the search';
COMMENT ON COLUMN search_metric.search_time_ms IS 'Total search time in milliseconds';
COMMENT ON COLUMN search_metric.embedding_time_ms IS 'Vertex AI embedding generation time in milliseconds';
COMMENT ON COLUMN search_metric.oracle_time_ms IS 'Oracle vector search time in milliseconds';
COMMENT ON COLUMN search_metric.similarity_score IS 'Representative similarity score for search results';


-- Indexes for performance optimization

-- Vector similarity search indexes for product embeddings (HNSW INMEMORY)
-- docs:start-hnsw-index
CREATE VECTOR INDEX product_embedding_idx ON product (embedding)
ORGANIZATION INMEMORY NEIGHBOR GRAPH
DISTANCE COSINE
WITH TARGET ACCURACY 95
PARAMETERS (TYPE HNSW, NEIGHBORS 40, EFCONSTRUCTION 500);
-- docs:end-hnsw-index

-- Vector similarity index for embedding cache (HNSW INMEMORY)
CREATE VECTOR INDEX embedding_cache_embedding_idx ON embedding_cache (embedding)
ORGANIZATION INMEMORY NEIGHBOR GRAPH
DISTANCE COSINE
WITH TARGET ACCURACY 95
PARAMETERS (TYPE HNSW, NEIGHBORS 40, EFCONSTRUCTION 500);




-- Standard B-tree indexes for product table
CREATE INDEX product_category_idx ON product (category)
ANNOTATIONS (
    Display 'Product category lookup'
);
CREATE INDEX product_in_stock_idx ON product (in_stock)
ANNOTATIONS (
    Display 'Product stock lookup',
    Data_Role 'availability'
);
CREATE INDEX product_created_at_idx ON product (created_at);


-- Store indexes for location queries
CREATE INDEX store_city_idx ON store (city);
CREATE INDEX store_state_idx ON store (state);
CREATE INDEX store_zip_idx ON store (zip);
CREATE INDEX store_location_idx ON store (latitude, longitude)
ANNOTATIONS (
    Display 'Seeded store coordinate lookup',
    Privacy 'Browser coordinates are not persisted'
);


-- Store inventory indexes for availability queries
CREATE INDEX store_product_inventory_store_idx ON store_product_inventory (store_id);
CREATE INDEX store_product_inventory_product_idx ON store_product_inventory (product_id);
CREATE INDEX store_product_inventory_status_idx ON store_product_inventory (stock_status)
ANNOTATIONS (
    Display 'Inventory status lookup',
    Data_Role 'availability'
);
CREATE INDEX store_product_inventory_product_status_idx ON store_product_inventory (product_id, stock_status);


-- Cache indexes for expiration and lookup
CREATE INDEX response_cache_expires_at_idx ON response_cache (expires_at);
CREATE INDEX response_cache_created_at_idx ON response_cache (created_at);


-- Embedding cache indexes
CREATE INDEX embedding_cache_model_idx ON embedding_cache (model);
CREATE INDEX embedding_cache_created_at_idx ON embedding_cache (created_at);
CREATE INDEX embedding_cache_hit_count_idx ON embedding_cache (hit_count DESC);
CREATE INDEX embedding_cache_last_accessed_idx ON embedding_cache (last_accessed DESC);


-- Search metrics indexes
CREATE INDEX search_metric_query_id_idx ON search_metric (query_id);
CREATE INDEX search_metric_user_id_idx ON search_metric (user_id);
CREATE INDEX search_metric_created_at_idx ON search_metric (created_at);
CREATE INDEX search_metric_similarity_idx ON search_metric (similarity_score);


-- Oracle Text indexes for full-text search on product
BEGIN
    CTX_DDL.CREATE_PREFERENCE('product_lexer', 'BASIC_LEXER');
    CTX_DDL.SET_ATTRIBUTE('product_lexer', 'index_text', 'YES');
END;

CREATE INDEX product_name_text_idx ON product (name)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS ('LEXER product_lexer SYNC (ON COMMIT)');

CREATE INDEX product_description_text_idx ON product (description)
INDEXTYPE IS CTXSYS.CONTEXT
PARAMETERS ('LEXER product_lexer SYNC (ON COMMIT)');


-- name: migrate-0001-down

-- Drop Oracle Text indexes
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX product_description_text_idx';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX product_name_text_idx';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;

BEGIN CTX_DDL.DROP_PREFERENCE('product_lexer'); EXCEPTION WHEN OTHERS THEN NULL; END;


-- Drop search metric indexes
BEGIN EXECUTE IMMEDIATE 'DROP INDEX search_metric_similarity_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX search_metric_created_at_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX search_metric_user_id_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX search_metric_query_id_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

-- Drop embedding cache indexes
BEGIN EXECUTE IMMEDIATE 'DROP INDEX embedding_cache_last_accessed_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX embedding_cache_hit_count_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX embedding_cache_created_at_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX embedding_cache_model_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;


-- Drop response cache indexes
BEGIN EXECUTE IMMEDIATE 'DROP INDEX response_cache_created_at_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX response_cache_expires_at_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;


-- Drop product indexes
BEGIN EXECUTE IMMEDIATE 'DROP INDEX product_created_at_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX product_in_stock_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX product_category_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX store_zip_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX store_state_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX store_city_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX store_location_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;


-- Drop store inventory indexes
BEGIN EXECUTE IMMEDIATE 'DROP INDEX store_product_inventory_product_status_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX store_product_inventory_status_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX store_product_inventory_product_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX store_product_inventory_store_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;


BEGIN EXECUTE IMMEDIATE 'DROP INDEX product_embedding_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP INDEX embedding_cache_embedding_idx'; EXCEPTION WHEN OTHERS THEN NULL; END;



BEGIN EXECUTE IMMEDIATE 'DROP TABLE search_metric PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE embedding_cache PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE response_cache PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE store_product_inventory PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE store PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE product PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
