from __future__ import annotations

import contextlib
from typing import TYPE_CHECKING, Any

import pytest
from litestar.testing import AsyncTestClient

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator
    from litestar import Litestar


async def _bootstrap_test_schema(session: Any) -> None:
    """Ensure integration-test tables and seed data exist."""
    await session.execute(
        """
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE product (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    name VARCHAR2(255) NOT NULL,
                    description VARCHAR2(4000),
                    price NUMBER(10, 2),
                    category VARCHAR2(100),
                    sku VARCHAR2(100) UNIQUE,
                    in_stock BOOLEAN DEFAULT TRUE,
                    metadata JSON,
                    embedding VECTOR(768, FLOAT32),
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT ON NULL FOR INSERT AND UPDATE CURRENT_TIMESTAMP NOT NULL
                )
            ';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
        """
    )
    await session.execute(
        """
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE response_cache (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    cache_key VARCHAR2(255) UNIQUE NOT NULL,
                    response_data JSON NOT NULL,
                    expires_at TIMESTAMP WITH TIME ZONE,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                )
            ';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
        """
    )
    await session.execute(
        """
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE embedding_cache (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    text_hash VARCHAR2(255) NOT NULL,
                    embedding VECTOR(768, FLOAT32) NOT NULL,
                    model VARCHAR2(100) NOT NULL,
                    hit_count NUMBER DEFAULT 0,
                    last_accessed TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT embedding_cache_uk UNIQUE (text_hash, model)
                )
            ';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
        """
    )
    await session.execute(
        """
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE intent_exemplar (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    intent VARCHAR2(100) NOT NULL,
                    phrase VARCHAR2(1000) NOT NULL,
                    embedding VECTOR(768, FLOAT32),
                    confidence_threshold NUMBER(3, 2) DEFAULT 0.7,
                    usage_count NUMBER DEFAULT 0,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT ON NULL FOR INSERT AND UPDATE CURRENT_TIMESTAMP NOT NULL,
                    CONSTRAINT intent_exemplar_uk UNIQUE (intent, phrase)
                )
            ';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
        """
    )
    await session.execute(
        """
        MERGE INTO product p
        USING (SELECT :sku AS sku FROM dual) src
        ON (p.sku = src.sku)
        WHEN NOT MATCHED THEN
            INSERT (name, description, price, category, sku, in_stock)
            VALUES (:name, :description, :price, :category, :sku, TRUE)
        """,
        sku="SEED-SKU-001",
        name="Seed Coffee Product",
        description="Baseline product seeded for integration tests",
        price=9.99,
        category="Coffee",
    )
    await session.commit()


@pytest.fixture
async def client(app: Litestar) -> AsyncGenerator[AsyncTestClient, None]:
    """Create test client."""
    async with AsyncTestClient(app=app) as c:
        yield c


@pytest.fixture
def app() -> Litestar:
    """Create test app instance."""
    from app.server.asgi import create_app

    return create_app()


@pytest.fixture
async def driver() -> AsyncGenerator[Any, None]:
    """Provide SQLSpec driver for tests."""
    from app.config import db, db_manager

    with contextlib.suppress(Exception):
        if db.pool_instance is not None:
            await db.close_pool()
            db.pool_instance = None

    try:
        async with db_manager.provide_session(db) as session:
            await _bootstrap_test_schema(session)
            yield session
    finally:
        # pytest-anyio creates a fresh event loop per test by default.
        # Closing the shared pool avoids loop-bound pool reuse across tests.
        with contextlib.suppress(Exception):
            await db.close_pool()
        db.pool_instance = None


@pytest.fixture
async def product_service(driver: Any) -> Any:
    """Provide ProductService for testing."""
    from app.domain.products.services import ProductService

    return ProductService(driver)


@pytest.fixture
async def cache_service(driver: Any) -> Any:
    """Provide CacheService for testing."""
    from app.domain.system.services import CacheService

    return CacheService(driver)


@pytest.fixture
async def intent_service(driver: Any) -> Any:
    """Provide IntentService for testing."""
    from unittest.mock import MagicMock

    from app.domain.chat.services import IntentService

    # Create mock services
    mock_vertex = MagicMock()
    mock_exemplar = MagicMock()

    # Service with optional cache
    return IntentService(driver=driver, vertex_ai_service=mock_vertex, exemplar_service=mock_exemplar)
