# Copyright 2026 Google LLC
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import asyncio
import contextlib
from pathlib import Path
from typing import TYPE_CHECKING

import pytest
from litestar.testing import AsyncTestClient

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator

    from litestar import Litestar
    from sqlspec.adapters.oracledb import OracleAsyncDriver

    from app.domain.chat.services import IntentService
    from app.domain.products.services import ProductService
    from app.domain.system.services import CacheService


# Pin every integration test in this directory to a single xdist worker. The
# Oracle connection pool + fixture-loaded data are shared mutable state; running
# them across two workers causes pool-handle errors and TRUNCATE races.
def pytest_collection_modifyitems(config: pytest.Config, items: list[pytest.Item]) -> None:
    del config  # unused
    marker = pytest.mark.xdist_group(name="oracle_integration")
    for item in items:
        item.add_marker(marker)


async def _bootstrap_test_schema(session: OracleAsyncDriver) -> None:
    """Ensure integration-test tables and seed data exist."""
    await session.execute(
        """
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE product (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    name VARCHAR2(255) NOT NULL,
                    description VARCHAR2(4000),
                    price NUMBER(10, 2),
                    category VARCHAR2(100),
                    sku VARCHAR2(100) UNIQUE,
                    in_stock BOOLEAN DEFAULT TRUE,
                    metadata JSON,
                    embedding VECTOR(3072, FLOAT32),
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT ON NULL FOR INSERT AND UPDATE CURRENT_TIMESTAMP NOT NULL
                )
            ';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
        """
    )
    await session.execute(
        """
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE response_cache (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    cache_key VARCHAR2(255) UNIQUE NOT NULL,
                    response_data JSON NOT NULL,
                    expires_at TIMESTAMP WITH TIME ZONE,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
                )
            ';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
        """
    )
    await session.execute(
        """
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE embedding_cache (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    text_hash VARCHAR2(255) NOT NULL,
                    embedding VECTOR(3072, FLOAT32) NOT NULL,
                    model VARCHAR2(100) NOT NULL,
                    hit_count NUMBER DEFAULT 0,
                    last_accessed TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT embedding_cache_uk UNIQUE (text_hash, model)
                )
            ';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
        """
    )
    await session.execute(
        """
        BEGIN
            EXECUTE IMMEDIATE '
                CREATE TABLE intent_exemplar (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    intent VARCHAR2(100) NOT NULL,
                    phrase VARCHAR2(1000) NOT NULL,
                    embedding VECTOR(3072, FLOAT32),
                    confidence_threshold NUMBER(3, 2) DEFAULT 0.7,
                    usage_count NUMBER DEFAULT 0,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT ON NULL FOR INSERT AND UPDATE CURRENT_TIMESTAMP NOT NULL,
                    CONSTRAINT intent_exemplar_uk UNIQUE (intent, phrase)
                )
            ';
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE != -955 THEN
                    RAISE;
                END IF;
        END;
        """
    )
    await session.commit()


async def _seed_marker_product(session: OracleAsyncDriver) -> None:
    """Insert the deterministic marker product used by integration tests.

    Runs after fixture loading + truncation so the marker survives the reset.
    Tests reference it via ``WHERE sku = 'SEED-SKU-001'``.
    """
    await session.execute(
        """
        MERGE INTO product p
        USING (SELECT :sku AS sku FROM dual) src
        ON (p.sku = src.sku)
        WHEN NOT MATCHED THEN
            INSERT (name, description, price, category, sku, in_stock)
            VALUES (:name, :description, :price, :category, :sku, TRUE)
        """,
        sku="SEED-SKU-001",
        name="Seed Coffee Product",
        description="Baseline product seeded for integration tests",
        price=9.99,
        category="Coffee",
    )
    await session.commit()


@pytest.fixture
async def client(app: Litestar) -> AsyncGenerator[AsyncTestClient, None]:
    """Create test client."""
    async with AsyncTestClient(app=app) as c:
        yield c


@pytest.fixture
def app() -> Litestar:
    """Create test app instance."""
    from app.server.asgi import create_app

    return create_app()


async def _truncate_fixture_tables(session: OracleAsyncDriver) -> None:
    """Wipe fixture-managed tables so each test session starts from a known state.

    Mirrors the accelerator pattern: schema is durable, data is ephemeral. This
    purges any zero-vector pollution left by prior ``coffee load-fixtures`` runs
    against the dev container so vector-search assertions stay deterministic.
    """
    for table in ("intent_exemplar", "product", "store"):
        with contextlib.suppress(Exception):
            await session.execute(f"TRUNCATE TABLE {table}")
    await session.commit()


async def _load_app_fixtures(session: OracleAsyncDriver) -> None:
    """Load the canonical .json.gz fixtures into the test database.

    Uses the same loader the ``coffee load-fixtures`` CLI uses, so the test DB
    matches the production-app data shape (122 products with valid 3072-dim
    embeddings, intent exemplars, etc.). The fixture files are checked into
    ``src/app/db/fixtures/`` and updated by Ch 1.5's exemplar regen plumbing.
    """
    from app.db.utils import COFFEE_SHOP_TABLES
    from app.lib.settings import get_settings
    from app.utils.fixtures import FixtureLoader

    settings = get_settings()
    fixtures_dir = Path(settings.db.FIXTURE_PATH)
    if not await asyncio.to_thread(fixtures_dir.exists):
        return
    loader = FixtureLoader(
        fixtures_dir=fixtures_dir,
        driver=session,
        table_order=COFFEE_SHOP_TABLES,
        expected_vector_dim=settings.vertex_ai.EMBEDDING_DIMENSIONS,
    )
    await loader.load_all_fixtures()


@pytest.fixture
async def driver() -> AsyncGenerator[OracleAsyncDriver, None]:
    """Provide SQLSpec driver for tests against a freshly-seeded DB.

    The integration setup pipeline:
        1. Bootstrap schema (idempotent CREATE TABLE)
        2. Truncate fixture-owned tables (purge cross-test pollution)
        3. Load .json.gz fixtures (122 products + exemplars + stores)
        4. Insert the SEED-SKU-001 marker the older tests rely on
    """
    from app.config import db, db_manager

    with contextlib.suppress(Exception):
        await db.close_pool()

    try:
        async with db_manager.provide_session(db) as session:
            await _bootstrap_test_schema(session)
            await _truncate_fixture_tables(session)
            await _load_app_fixtures(session)
            await _seed_marker_product(session)
            yield session
    finally:
        # pytest-anyio creates a fresh event loop per test by default.
        # Closing the shared pool avoids loop-bound pool reuse across tests.
        with contextlib.suppress(Exception):
            await db.close_pool()


@pytest.fixture
async def product_service(driver: OracleAsyncDriver) -> ProductService:
    """Provide ProductService for testing."""
    from app.domain.products.services import ProductService

    return ProductService(driver)


@pytest.fixture
async def cache_service(driver: OracleAsyncDriver) -> CacheService:
    """Provide CacheService for testing."""
    from app.domain.system.services import CacheService

    return CacheService(driver)


@pytest.fixture
async def intent_service(driver: OracleAsyncDriver) -> IntentService:
    """Provide IntentService for testing."""
    from unittest.mock import MagicMock

    from app.domain.chat.services import IntentService

    mock_vertex = MagicMock()
    mock_exemplar = MagicMock()

    return IntentService(driver=driver, vertex_ai_service=mock_vertex, exemplar_service=mock_exemplar)
